### ISSUE TITLE
interpolate widget crash and weid behavior

### ISSUE THREAD

**Issue by borondics** [markotoplak/orange-infrared#49]
The new interpolate widget is half-working.

If I use "Linear Interval" and pipe that into a Curves widget I get errors (one went to the main Orange error reporting queue, the other one is this:
```
Traceback (most recent call last):
  File "/Users/borondics/Documents/Prog/Python/orange-infrared/orangecontrib/infrared/widgets/owcurves.py", line 545, in rescale_current_view_y
    self.plot.vb.setYRange(ymin, ymax, padding=0.0)
  File "/Users/borondics/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 605, in setYRange
    self.setRange(yRange=[min, max], update=update, padding=padding)
  File "/Users/borondics/anaconda3/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 532, in setRange
    raise Exception("Cannot set range [%s, %s]" % (str(mn), str(mx)))
Exception: Cannot set range [nan, nan]
```

Also, we need some decent documentation immediately as we release the widgets, because otherwise nobody will understand what is what (including me).

**Comment by markotoplak** [comment]
This is a problem in the Curves widget which appears is some cases when there are lines with many NaN values. NaN values are used to denote unknown values - when your interpolation interval is wider than the data, some values witll be unknown.

I have not figured out yet exactly which combination of unknown values is problematic to PyQtGraph. The order of curves also influences the bug.

**Comment by markotoplak** [comment]
Tried to solve it with commit c68af47
